const metadata = {
  id: 5,
  name: `Responding to a Violent Disaster with Mass Casualties`,
  metadata: {
    description: [`This case shows how chaplains work with larger disaster relief organizations. One example is the Disaster Spiritual Care component of the American Red Cross.* It shows how chaplains transition from their day-to-day careers to disaster response, the process of integrating into highly complex disaster response operations, and the unique considerations of disaster response in the case of a violent attack with many victims.`,'While the case models the detailed planning process followed by chaplains assigned to assist families, its main point of tension is the appropriateness of overtly religious responses to identity-based violence. It notes the difficulty that impartial, non-sectarian spiritual care volunteers may encounter when responding to a violent disaster.', 'Finally, it ends with the chaplain directly working with the family, which has clearly experienced discord in the past over an individual family member’s struggle with their child’s identity. The chaplain sees clear elements of division and pain and attempts to begin a dialogue that can focus on positive, loving aspects of the relationship, redirecting energy in a healing direction.', '* Note: this case does not intend to represent a specific real-life disaster response organization. We thank Tim Serban, System Executive Director of Spiritual Health, Providence St. Joseph Health, and retired chaplain Earl Johnson for their assistance.'],
    objectives: [`Consider the role of spiritual care response in large-scale disasters`, `Illustrate the multi-stage vetting process that responsible disaster relief organizations follow to ensure appropriate spiritual care at disaster sites`, `Reflect on how individual chaplains might integrate a deep emotional response to a disaster and/or others’ public statements pertaining thereto`, `Explore how religious organizations not staffed by chaplains can or should respond todisasters, and what that response should include`, `Discuss how chaplains can anticipate and respond to potential religious trauma in disaster victims and differentiate a chaplain’s contribution`],
    themes: [`Local and state-level police, as well as other local emergency responders, who may come across either professional chaplains or untrained volunteers from religious organizations`, `Seminary/divinity/theological school students planning on congregational careers, where they might be positioned to respond to local disasters`, `System-level executives overseeing chaplains who could be trained to respond to local or national disasters`, `Chaplains employed by institutions willing to release chaplains to respond to disasters`],

  },
  image:
    "https://chaplaincy-innovation-lab-lessons.s3.us-east-1.amazonaws.com/2025-01/220606-h-ls763-0011.jpg",
  slug: "responding-to-a-violent-disaster-with-mass-casualties",
  title: `Responding to a Violent Disaster with Mass Casualties`,
}

export default metadata;